### ISSUE TITLE
f-tag:  Request for max-width with ellipsis in text

### ISSUE THREAD

**Issue by gammaSpeck** [cldcvr/flow-core#156]
### **Is your feature request related to a problem? Please describe.**

![image](https://github.com/cldcvr/flow-core/assets/39631861/1cc2a37e-a4eb-49cf-9c10-dde0b13150a1)

### **Describe the solution you'd like**
We need a way to have a maxWidth on f-tag that will make the inner label collapse into **ellipsis** when it overflows the max Width

### **Describe alternatives you've considered**
Right now, using a parent f-div or setting inline css max width cuts the tag abruptly

**Comment by vikas-cldcvr** [comment]
@gammaSpeck 

Please follow these 2 steps
1. Since it very unique case where we have flow1 multiselect and router-link with dynamic tags :  add f-div in is attribute + width="100%"
2. Update flow-core to ` "@cldcvr/flow-core": "2.0.5",`

<img width="944" alt="Screenshot 2023-10-16 at 4 42 09 PM" src="https://github.com/cldcvr/flow-core/assets/67629551/f52eb7c9-c3d1-4a76-bc17-1b6cd67ebad5">


<img width="220" alt="Screenshot 2023-10-16 at 4 49 30 PM" src="https://github.com/cldcvr/flow-core/assets/67629551/899a7ef8-7e39-49eb-a49d-19989abd9460">
